#!/usr/bin/env bash
# This script displays formatted content of the /etc/passwd file

while IFS=: read -r username password userid _ userInfo home shell; do
    echo "The user $username is part of the $userid gang, lives in $home and rides $shell. $userid's place is protected by the passcode $password, more info about the user here: $userInfo"
done < /etc/passwd
